@abstract
class_name ShopSegment
extends Node2D

@export var segment_type:SEGMENT_TYPE
@export var segment_availability:SEGMENT_AVAILABILITY

enum SEGMENT_AVAILABILITY {ENCOUNTER, ROUND_END, BOTH}
enum SEGMENT_TYPE {SERVICES, UTILITY, DISPOSABLE_TRANSMITTERS, NEW_CARTRIDGES, UPGRADES}
